### ISSUE TITLE
Finalize name

### ISSUE THREAD

**Issue by gvn** [mozilla/foxlight#31]
We're currently using Foxlight, but I keep seeing Fox*lite* pop up.

Let's choose which one it's going to be before we get too far along. It affects #9 at a minimum.

CC: @vazquez @cassiemc

**Comment by cassiemc** [comment]
Actually wondering if we want to call it foxlight at all. It makes me think it has something to do with firefox.

**Comment by gvn** [comment]
I like it, but I could see that.

**Comment by cassiemc** [comment]
@gvn Presumably this is best as a single word?

**Comment by vazquez** [comment]
Ideally, yes!

**Comment by gvn** [comment]
Yep, that'd be excellent. :+1:

**Comment by simonwex** [comment]
A small note from this morning's meeting. 

The target audience is developers who are starting a new site that should implement the MoFo style guidelines. This will show up in NPM and under our Mozilla Github org.

I don't mind `foxlight` or `foxlite`. If we want something that's not associated with Firefox, the world is our oyster. `dapper`, `boots`, etc

**Comment by cassiemc** [comment]
@simonwex To clarify then, it wouldn't ever be used within the CMS itself, nor would it be used without the CMS for non-developers? I recall lots of community members using makerstrap.

**Comment by gvn** [comment]
Other ideas (that are available on npm too): 

`lisica` (Bosnian word for "fox")
`vos` (Dutch)
`raposo` (Galician)

**Comment by gvn** [comment]
TBH I do really like Foxlight, so that'd be my vote.

**Comment by cassiemc** [comment]
@gvn Elaborate on why you like it?

**Comment by gvn** [comment]
It's simple and catchy. I think "light" reflects the goal of it being a lightweight design system as well as general positivity (and it has a light feel to it, literally). "Fox", well, that's just Mozilla.

**Comment by cassiemc** [comment]
What about Mozlight?

**Comment by cassiemc** [comment]
Actually, I prefer Mozlite, if we are referring to a lightweight system.

**Comment by cassiemc** [comment]
'light' is still problematic as could be misspelled lite. So while 'mozlight' solves one problem (decoupling from firefox) it doesn't solve the other. Here's a brainstorming doc, feel free to contribute: https://docs.google.com/document/d/1N5UDM_l9wTQ1bZdwMX3z-pmowopYADG2RpZxpVOkq28/edit

**Comment by cassiemc** [comment]
Current frontrunners are Mozstyles (or Moztiles) and Mozmaker. I am leaning toward the latter for ease of spelling.

**Comment by vazquez** [comment]
Voted on the doc. I like Mozmaker the best. :ok_hand:

**Comment by cassiemc** [comment]
Let's go with Mozmaker!
